package cafe;

public enum ErrType
{
    NONE, ALONE, CARD_LAID, INCOMPLETE_CIRCLE, ONLY_IN_CIRCLE, NO_CARD_LAID, NO_CARD_SELECTED, SB_ELSES_TURN, SEAT_IS_TAKEN, SEX_INEQUALITY, TABLE_MISMATCH, TOO_MANY_HANDCARDS
}
