package cafe;

public enum ErrType
{
    NONE,
    ALONE,
    CARD_LAID,
    CIRCLE_INCOMPLETE,
    CIRCLE_WRONG_SEX,
    CIRCLE_WRONG_TABLE,
    CIRCLE_UNSUITABLE_TABLE,
    NO_CARD_LAID,
    NO_CARD_SELECTED,
    SB_ELSES_TURN,
    SEAT_IS_TAKEN,
    SEX_IMBALANCE,
    TABLE_MISMATCH,
    TOO_MANY_HANDCARDS
}
